### ISSUE TITLE
Easy edit of NPC skills

### ISSUE THREAD

**Issue by kdomke** [Naresea/splittermond4foundry#17]
While for PCs the regular workflow would be to generate them in Genesis and import them, NPCs will normally be edited in Foundry itself.

I would like the possibility to just edit the skills in the list, not klick the edit icon for each of them, look for the correct field, edit it there, close, search for next skill...

Great work, btw!

**Comment by kdomke** [comment]
If you are interested in a colab, let me know.

**Comment by Naresea** [comment]
Would it be ok to have a checkbox somewhere on the character sheet "edit NPC" that toggles direct inputs for skills etc?
One thing I always diskliked about the pathfinder 2 system was how easy it is to accidentally edit your characters during play... one wrong click and suddenly your a master of longswords instead of an expert. :D 

The "edit-button + dialog" solves that but makes it less convenient to edit values...

**Comment by kdomke** [comment]
sounds great!

**Comment by Naresea** [comment]
Ok, it ended up not having a checkbox but instead some normal form fields. :D 
Should be much easier to setup creatures now than it was before.

While I was at it I also changed the "weapons". They are no longer items, but instead also a couple of fields where you can enter the correct values. Safes the trouble of assigning attributes and modifiers that are not given in official stat blocks (for monster weapons).

Please note that the datamodel for NPCs changed, though. Old NPCs won't carry over their skills.
